print ('=============================================================================================')
print ()
print ()
name = input("  >  I would like to know your name. What is your name? > " )
print ()
print ( "  >  Hello, " + name + "! Nice to meet you!" )
print ()
print ()
input ('============================== [ >> Press ENTER to continue. << ] ============================')
print ()
print ()
age = input("  >  Can you tell me how old you are, " + name + "? > " )
print ()
print ( "  >  So you said you're " + age + " years old, " + name + "? Alright!")
print ()
print ()
input ('============================== [ >> Press ENTER to continue. << ] ============================')
print ()
print ()
year = input("  >  I see that you're going to Guttman College, " + name + ". What year are you in? > " )
print ()
print ( "  >  So you're currently in your " + year + " year, " + name + ".")
print ()
print ()
input ('============================== [ >> Press ENTER to continue. << ] ============================')
print ()
print ()
enjoy = input("  >  Are you enjoying yourself at Guttman, " + name + "? > " )
print ()
print ( "  >  Ah, " + enjoy + "? I see.")
print ()
print ()
input ('============================== [ >> Press ENTER to continue. << ] ============================')
print ()
print ()
answer = input("  >  I want to know if you like programming! Do you like programming, " + name + "? > " )
print ()
print ( "  >  Great! You said " + answer + "?" )
print ()
print ()
input ('============================== [ >> Press ENTER to continue. << ] ============================')
print ()
print ()
print ( "  >  Alright! Let me make sure I understand." )
input ()
print ( "  >  You are " + name + ", and you are " + age + " years old. You are in your " + year + " year at Guttman.")
input ()
print ( "  >  You said " + enjoy + " when I asked you if you're enjoying yourself here.")
input ()
print ()
input ('============================== [ >> Press ENTER to continue. << ] ============================')
print ()
print ()
print ( "  >  Very well! I believe it's time to begin. Let's learn some Python today, " + name + "!")
print ()
print ()
input ('================================ [ >> Press ENTER to exit. << ] ==============================')
